//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.FormFields = new HashSet<FormField>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<FormField> FormFields { get; set; }
    }
}
