//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMaker
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormField
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string fieldType { get; set; }
        public string defaultValue { get; set; }
        public Nullable<int> formId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
