//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA123
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.FormControls = new HashSet<FormControl>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<FormControl> FormControls { get; set; }
    }
}
